<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/8
 * Time: 11:03
 * 网站基本信息
 */

namespace Admin\Controller;
use Think\Controller;


class SetController extends BaseController
{
    private $Lable;
    private $Banner;


    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Lable=D('Lable');
        $this->Banner=D('Banner');
    }




    public function basic()
    {
        $data=$this->Lable->getLables();
        $this->assign('data',$data);
        $this->display();
    }

    public function basiced()
    {
        if(IS_POST){
          $data=$_POST;
            foreach($data as $val)
            {
                $flag = $this->Lable->editlable($val);
                if($flag===false)
                {
                    $this->error('编辑失败');break;
                }
            }

            if($flag){
                $this->success('编辑成功',U('Set/basic'));
            }else{
                $this->error('编辑失败');
            }
        }else{
           redirect(U('Set/basic'));
        }
    }

    public function banner()
    {
        $list=$this->Banner->getbanners(1);
        $this->assign('img',$list);
        $this->display();
    }

    Public function bannered()
    {
        $banners=$_FILES;
        foreach($banners as $key=>$val)
        {
            if(!empty($val['tmp_name']))
            {
                
            }
        }

    }

    public function banner1()
    {
        layout(false);
        $list=$this->Banner->getbanners(1);
        $this->assign('list',$list);
        $this->display();
    }


}